#ifndef ERROR_H
#define ERROR_H

typedef enum {
    BK_ERC_OK = 0,
    BK_ERC_ENGAGED,
    BK_ERC_NOT_CONNECTED,
    BK_ERC_PUBLISH,
    BK_ERC_NO_META,
    BK_ERC_INV_META,
    BK_ERC_NO_ID,
    BK_ERC_NO_SERVICE_IFC,
    BK_ERC_INV_SERVICE_IFC,
    BK_ERC_NO_SESSION_IFC,
    BK_ERC_NO_SESSION_IFC_PTR,
    BK_ERC_NO_SESSION_ID_PTR,
    BK_ERC_NO_SUCH_SERVICE,
    BK_ERC_TO_MUCH_SESSIONS,
    BK_ERC_NO_SUCH_SESSION,
    BK_ERC_NOT_IMPLEMENTED,
    BK_ERC_INV_IP_VERSION,
    BK_ERC_INV_ADDR_INFO,
    BK_ERC_NO_ADDR_INFO,
    BK_ERC_SOCKET_ERROR,
    BK_ERC_BIND_ERROR,
    BK_ERC_LISTEN_ERROR,
    BK_ERC_TALK_ERROR,
    BK_ERC_ACCEPT_ERROR,
    BK_ERC_NULL_BODY,
    BK_ERC_INV_CRC_TYPE,
    BK_ERC_RUNTIME_EXCEPTION,
} bk_error_t;

#endif // ERROR_H
